config/routes.rb
Rails.application.routes.draw do
  resources :users

  root "static_pages#home"

  get "/auth/spotify", :as => :sign_in
  get '/auth/:provider/callback', to: 'sessions#create'
  get "/signout" => "sessions#destroy", :as => :signout_user
  get '/add_to_playlist/:id/:playlist/:track' => "users#add_to_playlist", :as => :add_to_playlist

end

app/models/user.rb
class User < ActiveRecord::Base
  serialize :credentials, Hash

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["display_name"]
      user.email = auth["info"]["email"]
      user.image_url = auth["info"]["images"].first["url"]
      user.credentials = auth
      user.access_token = auth["credentials"]["token"]
      user.refresh_token = auth["credentials"]["refresh_token"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    flash[:notice] = "Signed In"
    redirect_to user_path(user)
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Signed Out"
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SpotifyTrack

  before_action :set_user, only: [:show, :edit, :update, :destroy, :add_to_playlist]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @spotify_user = RSpotify::User.new(@user.credentials)
    @lastfm = Lastfm.new(ENV['lastfm_key'],ENV['lastfm_secret_key'])
    @spotify_track = SpotifyTrack.grab(@user)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_to_playlist
    @spotify_user = RSpotify::User.new(@user.credentials)
    playlist = @spotify_user.playlists.detect { |pl| pl.id == params[:playlist] }
    tracks = [ RSpotify::Track.find(params[:track]) ]
    playlist.add_tracks!(tracks)
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpotifyPlaylistCreator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<%= link_to 'Sign in with Spotify', sign_in_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4 text-center">
      <h4><small>Now Playing for <%= @spotify_user.display_name %></small></h4>
      <hr/>
      <% if @spotify_track %>
      <div class="text-center">
        <%= image_tag @spotify_track.album.images.first["url"], class: 'img-circle', style: 'max-height: 200px;'  %>
      </div>
      <h5><%= @spotify_track.name %></h5>
      <h5><%= @spotify_track.artists.first.name %></h5>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
      <hr/>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Your Spotify Playlists</h3>
        </div>
        <ul class="list-group">
          <% @spotify_user.playlists.each do |playlist| %>
          <li class="list-group-item clearfix">
            <%= playlist.name %>
            <div class="pull-right">
              <% if @spotify_track %>
              <%= link_to icon('plus'), add_to_playlist_path(@user.id, playlist.id, @spotify_track.id), class: 'btn btn-primary', remote: :true %>
              <% end %>
            </div>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>